VKPCShop.WebApp/Areas/Admin/Controllers/BrandController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using VKPCShop.WebApp.Dtos;
using VKPCShop.WebApp.Services.Brands;

namespace VKPCShop.WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BrandController : BaseController
    {
        private readonly IBrandService _brandService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BrandController(IBrandService brandService, IWebHostEnvironment webHostEnvironment)
        {
            _brandService = brandService;
            _webHostEnvironment = webHostEnvironment;

        }
        public async Task<IActionResult> Index(string? keyword)
        {
            ViewBag.NotifyBrand = TempData["result"];
            var list = await _brandService.GetAll(keyword);
            return View(list);
        }
        [HttpPost]
        public async Task<IActionResult> Create(BrandDto dto)
        {
            if (!ModelState.IsValid)
            {
                TempData["result"] = "fail";
                return RedirectToAction("Index");
            }
            SaveImage(dto);
            var create = await _brandService.Create(dto);
            if (create)
            {
                TempData["result"] = "success";
                return RedirectToAction("Index");
            }
            TempData["result"] = "fail";
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var get = await _brandService.GetById(id);
            if (get != null)
            {
                return Json(new { status = true, name = get.Name });
            }
            return Json(new
            {
                status = false
            });
        }
        [HttpPost]
        public async Task<IActionResult> Update(BrandDto dto)
        {
            if (!ModelState.IsValid)
            {
                TempData["result"] = "fail";
                return RedirectToAction("Index");
            }
            if(dto.formFile != null)
            {
                SaveImage(dto);
            }
            var create = await _brandService.Update(dto);
            if (create)
            {
                TempData["result"] = "success";
                return RedirectToAction("Index");
            }
            TempData["result"] = "fail";
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            var delete = await _brandService.Delete(id);
            if (delete)
            {
                return Json(new {status = true });
            }
            return Json(new { status = false });
        }
        public void SaveImage(BrandDto dto)
        {
            string fileName = Guid.NewGuid().ToString() + "-" + dto.formFile.FileName;
            string targetPath = Path.Combine(_webHostEnvironment.WebRootPath, "admin\\images", fileName);
            using (var stream = new FileStream(targetPath, FileMode.Create))
            {
                dto.formFile.CopyTo(stream);
            }
            dto.Image = fileName;
        }
    }
}

VKPCShop.WebApp/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.IO;
using VKPCShop.WebApp.Dtos;
using VKPCShop.WebApp.Services.Brands;
using VKPCShop.WebApp.Services.Categories;
using VKPCShop.WebApp.Services.Products;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace VKPCShop.WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : BaseController
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly IBrandService _brandService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IProductService productService, ICategoryService categoryService, IBrandService brandService, IWebHostEnvironment webHostEnvironment)
        {
            _productService = productService;
            _categoryService = categoryService;
            _brandService = brandService;
            _webHostEnvironment = webHostEnvironment;

        }
        public async Task<IActionResult> Index(string? keyword, int pageIndex)
        {
            ViewBag.Result = TempData["success"];
            if (pageIndex == 0)
                pageIndex = 1;
            var dto = new PagingDto()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = 10
            };
            var paging = await _productService.GetAllAdmin(dto);
            return View(paging);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Price = 0;
            ViewBag.SalePrice = 0;
            ViewBag.Quantity = 0;
            ViewBag.Brands = await _brandService.GetAll(null);
            ViewBag.Categories = await _categoryService.GetAll(null);
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ProductDto dto)
        {
            // kiểm tra validation
            if (!ModelState.IsValid)
            {
                if (dto.BrandId != null)
                {
                    ViewBag.BrandId = dto.BrandId;
                }
                if (dto.CategoryId != null)
                {
                    ViewBag.CategoryId = dto.CategoryId;
                }
                if (dto.Name != null)
                {
                    ViewBag.Name = dto.Name;
                }
                if (dto.Price > 0)
                {
                    ViewBag.Price = dto.Price;
                }
                else
                {
                    ViewBag.Price = 0;
                }
                if (dto.SalePrice > 0)
                {
                    ViewBag.SalePrice = dto.SalePrice;
                }
                else
                {
                    ViewBag.SalePrice = 0;
                }
                if (dto.Quantity > 0)
                {
                    ViewBag.Quantity = dto.Quantity;
                }
                else
                {
                    ViewBag.Quantity = 0;
                }
                if (dto.Config != null)
                {
                    ViewBag.Config = dto.Config;
                }
                if (dto.Description != null)
                {
                    ViewBag.Description = dto.Description;
                }
                ViewBag.Brands = await _brandService.GetAll(null);
                ViewBag.Categories = await _categoryService.GetAll(null);
                return View(dto);
            }
            SaveImage(dto);
            var created = await _productService.Create(dto);
            if (created)
                TempData["success"] = "success";
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            ViewBag.Brands = await _brandService.GetAll(null);
            ViewBag.Categories = await _categoryService.GetAll(null);
            var product = await _productService.GetById(id);
            return View(product);
        }
        [HttpPost]
        public async Task<IActionResult> Update(ProductUpdateDto dto)
        {
            // kiểm tra validation
            if (!ModelState.IsValid)
            {
                if (dto.BrandId != null)
                {
                    ViewBag.BrandId = dto.BrandId;
                }
                if (dto.CategoryId != null)
                {
                    ViewBag.CategoryId = dto.CategoryId;
                }
                if (dto.Name != null)
                {
                    ViewBag.Name = dto.Name;
                }
                if (dto.Price > 0)
                {
                    ViewBag.Price = dto.Price;
                }
                else
                {
                    ViewBag.Price = 0;
                }
                if (dto.SalePrice > 0)
                {
                    ViewBag.SalePrice = dto.SalePrice;
                }
                else
                {
                    ViewBag.SalePrice = 0;
                }
                if (dto.Quantity > 0)
                {
                    ViewBag.Quantity = dto.Quantity;
                }
                else
                {
                    ViewBag.Quantity = 0;
                }
                if (dto.Config != null)
                {
                    ViewBag.Config = dto.Config;
                }
                if (dto.Description != null)
                {
                    ViewBag.Description = dto.Description;
                }
                ViewBag.Brands = await _brandService.GetAll(null);
                ViewBag.Categories = await _categoryService.GetAll(null);
                return View(dto);
            }
            if(dto.formFiles != null)
            {
                SaveImage(dto);
            }
            var updated = await _productService.Update(dto);
            if (updated)
                TempData["success"] = "success";
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            var deleted = await _productService.Delete(id);
            if (deleted)
                TempData["success"] = "success";
            return RedirectToAction("Index");
        }
        public void SaveImage(ProductDto dto)
        {
            string fileName = Guid.NewGuid().ToString() + "-" + dto.formFile.FileName;
            string targetPath = Path.Combine(_webHostEnvironment.WebRootPath, "admin\\images", fileName);
            using (var stream = new FileStream(targetPath, FileMode.Create))
            {
                dto.formFile.CopyTo(stream);
            }
            dto.Image = fileName;


            var listImage = new List<string>();
            if (dto.formFiles != null)
            {
                foreach (var item in dto.formFiles)
                {
                    var image = Guid.NewGuid().ToString() + "-" + item.FileName;
                    string targetPaths = Path.Combine(_webHostEnvironment.WebRootPath, "admin\\images", image);
                    using (var streams = new FileStream(targetPaths, FileMode.Create))
                    {
                        item.CopyTo(streams);
                    }
                    listImage.Add(image);
                }
            }
            dto.Images = listImage;
        }
        public void SaveImage(ProductUpdateDto dto)
        {
            if(dto.formFile != null)
            {
                string fileName = Guid.NewGuid().ToString() + "-" + dto.formFile.FileName;
                string targetPath = Path.Combine(_webHostEnvironment.WebRootPath, "admin\\images", fileName);
                using (var stream = new FileStream(targetPath, FileMode.Create))
                {
                    dto.formFile.CopyTo(stream);
                }
                dto.Image = fileName;
            }
            var listImage = new List<string>();
            if(dto.formFiles != null)
            {
                foreach (var item in dto.formFiles)
                {
                    var image = Guid.NewGuid().ToString() + "-" + item.FileName;
                    string targetPaths = Path.Combine(_webHostEnvironment.WebRootPath, "admin\\images", image);
                    using (var streams = new FileStream(targetPaths, FileMode.Create))
                    {
                        item.CopyTo(streams);
                    }
                    listImage.Add(image);
                }
            }
            dto.Images = listImage;
        }
    }
}

VKPCShop.WebApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.WebSockets;
using VKPCShop.Data.Entities;
using VKPCShop.WebApp.Constant;
using VKPCShop.WebApp.Services.Brands;
using VKPCShop.WebApp.Services.Images;
using VKPCShop.WebApp.Services.Products;
using VKPCShop.WebApp.ViewModel;
using static Microsoft.Extensions.Logging.EventSource.LoggingEventSource;

namespace VKPCShop.WebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IBrandService _brandService;
        private readonly IImageService _imageService;
        public ProductController(IProductService productService, IBrandService brandService, IImageService imageService)
        {
            _productService = productService;
            _brandService = brandService;
            _imageService = imageService;
        }
        public async Task<IActionResult> Index(int? categoryId, bool ascending, bool descending, bool bestSell, int? price, List<string>? brands, string? keyword, bool sale, bool casepc)
        {
            var cartSession = HttpContext.Session.GetString("cartSession");
            if (cartSession != null)
            {
                ViewBag.CartNumber = JsonConvert.DeserializeObject<List<CartVm>>(cartSession).Count();
            }
            else { ViewBag.CartNumber = 0; }
            if (keyword != null)
            {
                ViewBag.Keyword = keyword;
            }
            ViewBag.CategoryId = categoryId;
            if (ascending)
            {
                ViewBag.FilterName = FilterProductConstant.Ascending;
            }
            else if (descending)
            {
                ViewBag.FilterName = FilterProductConstant.Descending;
            }
            else if (bestSell)
            {
                ViewBag.FilterName = FilterProductConstant.BestSell;
            }
            else
            {
                ViewBag.FilterName = FilterProductConstant.Default;
            }
            if(brands.Count > 0)
            {
                ViewBag.BrandChecked = await _brandService.GetBrands(brands);
                ViewBag.ListBrand = brands;
            }
            else
            {
                ViewBag.BrandChecked = null;
            }
            if(price != null)
            {
                ViewBag.PriceCheck = price;
            }
            else
            {
                ViewBag.PriceCheck = 30;
            }
            ViewBag.Brand = await _brandService.GetAll(null);
            var products = await _productService.GetAll(bestSell,sale, casepc, categoryId, ascending, descending, price, brands, null, null, keyword);
            return View(products);
        }
        public async Task<IActionResult> Detail(int id)
        {
            var cartSession = HttpContext.Session.GetString("cartSession");
            if (cartSession != null)
            {
                ViewBag.CartNumber = JsonConvert.DeserializeObject<List<CartVm>>(cartSession).Count();
            }
            else { ViewBag.CartNumber = 0; }
            var detail = await _productService.GetById(id);
            if (detail != null)
            {
                ViewBag.Images = await _imageService.GetImagesByProductId(detail.Id);
                var brand = await _brandService.GetById(detail.BrandId);
                ViewBag.Brand = brand.Name;
                ViewBag.ProductsByBrand = await _productService.GetAll(false, false, false, null, false, false, null, null, detail.BrandId, detail.Id, null);
            }
            return View(detail);
        }
    }
}

VKPCShop.WebApp/Areas/Admin/Views/Product/Create.cshtml
@using VKPCShop.WebApp.Dtos;
@model ProductDto
@{
    ViewData["Title"] = "Create1";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    
}
@section Scripts{
    <script src="https://cdn.ckeditor.com/ckeditor5/36.0.1/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#txt_description'), {
                // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(err => {
                console.error(err.stack);
            });
        ClassicEditor
            .create(document.querySelector('#txt_config'), {
                // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(err => {
                console.error(err.stack);
            });
    </script>
}

<!-- BREADCRUMB-->
<section class="au-breadcrumb m-t-75">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item active">
                                    <a href="/Admin/Home">Trang chủ</a>
                                </li>
                                <li class="list-inline-item seprate">
                                    <span>/</span>
                                </li>
                                <li class="list-inline-item">Thêm sản phẩm</li>
                            </ul>
                        </div>
                        <a href="/Admin/Product"  class="au-btn au-btn-icon btn-secondary">
                            <i class="fa fa-chevron-left"></i> Quay lại
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- END BREADCRUMB-->


<div class="section__content section__content--p30">
    <div class="container-fluid">
        <div class="row m-t-30" style="background: white; padding: 1rem;">
            <div class="col-md-8">
                <form asp-controller="Product" asp-action="Create" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        @Html.ValidationMessageFor(m => m.BrandId,"", new { @class = "text-danger", @style="float: right;" })
                        <label asp-for="BrandId" class="control-label">Thương hiệu</label>
                        <select asp-for="BrandId" name="BrandId" class="form-control">
                            <option value="0">---Chọn---</option>
                            @foreach (var item in ViewBag.Brands)
                            {
                                if (ViewBag.BrandId == item.Id)
                                {
                                    <option value="@item.Id" selected>@item.Name</option>
                                }
                                <option value="@item.Id">@item.Name</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        @Html.ValidationMessageFor(m => m.CategoryId,"", new { @class = "text-danger", @style="float: right;" })
                        <label asp-for="CategoryId" class="control-label">Danh mục</label>
                        <select asp-for="CategoryId" name="CategoryId" class="form-control">
                            <option value="0">---Chọn---</option>
                            @foreach (var item in ViewBag.Categories)
                            {
                                if (ViewBag.CategoryId == item.Id)
                                {
                                    <option value="@item.Id" selected>@item.Name</option>
                                }
                                <option value="@item.Id">@item.Name</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        @Html.ValidationMessageFor(m => m.Name,"", new { @class = "text-danger", @style="float: right;"})
                        <label asp-for="Name" class="control-label">Tên sản phẩm</label>
                        <input asp-for="Name" class="form-control" name="name" value="@ViewBag.Name" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @Html.ValidationMessageFor(m => m.Price,"", new { @class = "text-danger", @style="float: right;"})
                        <label asp-for="Price" class="control-label">Giá</label>
                        <input type="number" asp-for="Price" class="form-control" name="price" value="@ViewBag.Price" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @Html.ValidationMessageFor(m => m.SalePrice,"", new { @class = "text-danger", @style="float: right;"})
                        <label asp-for="SalePrice" class="control-label">Giá khuyến mãi</label>
                        <input type="number" asp-for="SalePrice" class="form-control" name="salePrice" value="@ViewBag.SalePrice" />
                        <span asp-validation-for="SalePrice" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @Html.ValidationMessageFor(m => m.Quantity,"", new { @class = "text-danger", @style="float: right;"})
                        <label asp-for="Quantity" class="control-label">Số lượng</label>
                        <input type="number" asp-for="Quantity" class="form-control" name="quantity" value="@ViewBag.Quantity" />
                        <span asp-validation-for="Quantity" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @Html.ValidationMessageFor(m => m.Config,"", new { @class = "text-danger", @style="float: right;"})
                        <label asp-for="Config" class="control-label">Cấu hình</label>
                        <textarea id="txt_config" asp-for="Config" name="config" class="form-control">@ViewBag.Config</textarea>
                        <span asp-validation-for="Config" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @Html.ValidationMessageFor(m => m.Description,"", new { @class = "text-danger", @style="float: right;"})
                        <label asp-for="Description" class="control-label">Mô tả</label>
                        <textarea id="txt_description" asp-for="Description" name="description" class="form-control">@ViewBag.Description</textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @Html.ValidationMessageFor(m => m.formFile,"", new { @class = "text-danger", @style="float: right;"})
                        <label asp-for="formFile" class="control-label">Chọn ảnh</label>
                        <input asp-for="formFile" type="file" id="file-input" name="formFile" class="form-control-file">
                        <span asp-validation-for="formFile" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @Html.ValidationMessageFor(m => m.formFiles,"", new { @class = "text-danger", @style="float: right;"})
                        <label asp-for="formFiles" class="control-label">Chọn ảnh Slide</label>
                        <input asp-for="formFiles" type="file" id="file-multiple-input" name="formFiles" multiple="" class="form-control-file">
                        <span asp-validation-for="formFiles" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Lưu" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

VKPCShop.WebApp/Areas/Admin/Views/Product/Index.cshtml
@using VKPCShop.WebApp.Dtos;
@model PagingResult<ProductDto>
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@if (ViewBag.Result == "success")
{
    @section Notify{
    <script>
        $(document).ready(function () {
            $.notify("Thành công!", "success");
        });
    </script>
    }
}

<style>
    .input-addz{
        width: 100%;
        border: 1px solid silver;
        font-size: 15px;
        padding: 5px 0;
    }

    #border-pagination {
        margin: 0 auto;
        padding: 0;
        text-align: center;
        margin-top: 5px;
    }

        #border-pagination li {
            display: inline;
        }

            #border-pagination li a {
                display: block;
                text-decoration: none;
                color: #000;
                padding: 5px 10px;
                border: 1px solid #ddd;
                float: left;
            }

            #border-pagination li a {
                -webkit-transition: background-color 0.4s;
                transition: background-color 0.4s
            }

                #border-pagination li a.active {
                    background-color: #4caf50;
                    color: #fff;
                }

                #border-pagination li a:hover:not(.active) {
                    background: #ddd;
                }
</style>

<!-- BREADCRUMB-->
<section class="au-breadcrumb m-t-75">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item active">
                                    <a href="/Admin/Home">Trang chủ</a>
                                </li>
                                <li class="list-inline-item seprate">
                                    <span>/</span>
                                </li>
                                <li class="list-inline-item">Sản phẩm</li>
                            </ul>
                        </div>
                        <a href="/Admin/Product/Create" class="au-btn au-btn-icon au-btn--green">
                            <i class="zmdi zmdi-plus"></i> THÊM SẢN PHẨM
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- END BREADCRUMB-->
<!-- STATISTIC-->
<div class="section__content section__content--p30">
    <div class="container-fluid">
        <div class="row m-t-30">
            <div class="col-md-12">
                <!-- DATA TABLE-->
                <div class="table-responsive m-b-40">
                    <form asp-controller="Brand" asp-action="Index" method="get" style="margin-left: 1rem;padding: 0.3rem 0.5rem;border-radius: 5px; font-size: 13px; float: right; background: white;">
                        <input type="text" placeholder="Tìm kiếm..." name="keyword" />
                        <button type="submit"><i class="fa fa-search"></i></button>
                    </form>

                    <a href="/Admin/Product/Index" style="background: white; padding: 1px 0.5rem; border-radius: 5px; margin-top: 2px;color: #808080; float: right;"><i class="fa fa-refresh"></i></a>
                    <table class="table table-borderless table-data3">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Tên sản phẩm</th>
                                <th>Giá</th>
                                <th>Khuyến mãi</th>
                                <th>Đã bán</th>
                                <th>Hành động</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Items)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.Name</td>
                                    <td>@item.Price</td>
                                    <td>@item.SalePrice</td>
                                    <td>@item.Sold</td>
                                    <td>
                                        <div class="table-data-feature">
                                            <a href="/Admin/Product/Update?id=@item.Id">
                                                <button class="item icon-edit-product" data-toggle="tooltip" data-placement="top" title="" data-original-title="Sửa">
                                                <i class="zmdi zmdi-edit"></i>
                                                </button>
                                            </a>
                                            <a href="/Admin/Product/Delete?id=@item.Id">
                                                <button class="item btn-delete-product" data-toggle="tooltip" data-placement="top" title="" data-original-title="Xóa">
                                                    <i class="zmdi zmdi-delete"></i>
                                                </button>
                                            </a>
                                           
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    @if (Model.PageCount > 1)
                    {
                        <ul id="border-pagination">
                            @for (int i = 1; i <= Model.PageCount; i++)
                            {
                                if (Model.PageIndex == i)
                                {

                                    <li><a href="" class="active">@i</a></li>
                                }
                                else
                                {
                                    <li><a href="/Admin/Product?&pageIndex=@i&keyword=@ViewBag.Keyword">@i</a></li>
                                }
                            }
                            @{
                                int nextPage = 0;
                                if (Model.PageIndex + 1 <= Model.PageCount)
                                {
                                    nextPage = Model.PageIndex + 1;
                                }
                                else
                                {
                                    nextPage = Model.PageIndex;
                                }
                            }
                            <li><a href="/Admin/Product?&pageIndex=@nextPage&keyword=@ViewBag.Keyword">&raquo;</a></li>
                        </ul>
                    }
                </div>
                <!-- END DATA TABLE-->
            </div>
        </div>
    </div>
</div>
<!-- END STATISTIC-->